---
# handlers file for ansible-role-varnish
- name: Restart Varnish
  systemd:
    name: varnish
    daemon_reload: True
    state: restarted

- name: Reload Varnish
  service:
    name: varnish
    state: reloaded
